### ISSUE TITLE
yamllinter: failed build due to a "did not find expected key" error

### ISSUE THREAD

**Issue by qiaeru** [sijad/yaml-translation-utils#1]
When I'm using your yamllinter tool, I got a "did not find expected key" error that I don't understand. Indeed, the issue is on line 64 but this line is just a comment, not a key. Previous and next lines are okay.

Can you help me to find this issue? Thanks!

Error on TravisCI: https://travis-ci.org/milescellar/flarum-ext-french
Repo: https://github.com/milescellar/flarum-ext-french

**Comment by sijad** [comment]
hey, I've pasted contents of `flarum-ext-franch/locale/core.yml` in http://www.yamllint.com, it gives similar error. it seems a syntax error in `core.yml` but I'm not sure what's it.

**Comment by qiaeru** [comment]
Fixe,d thanks to the removal of redundant spaces on my YAML file. Thanks a lot!
